export const specialtyDepartmentOptions = [
  { label: 'General Medicine', value: 'General Medicine' },
  { label: 'Family Medicine', value: 'Family Medicine' },
  { label: 'Internal Medicine', value: 'Internal Medicine' },
  { label: 'Pediatrics', value: 'Pediatrics' },
  { label: 'Obstetrics and Gynecology', value: 'Obstetrics and Gynecology' },
  { label: 'Cardiology', value: 'Cardiology' },
  { label: 'Dermatology', value: 'Dermatology' },
  { label: 'Neurology', value: 'Neurology' },
  { label: 'Psychiatry', value: 'Psychiatry' },
  { label: 'Orthopedics', value: 'Orthopedics' },
  { label: 'Ophthalmology', value: 'Ophthalmology' },
  { label: 'ENT', value: 'ENT' },
  { label: 'Dentistry', value: 'Dentistry' },
  { label: 'Radiology', value: 'Radiology' },
  { label: 'Anesthesiology', value: 'Anesthesiology' },
  { label: 'Emergency Medicine', value: 'Emergency Medicine' },
  { label: 'Surgery', value: 'Surgery' },
  { label: 'Oncology', value: 'Oncology' },
  { label: 'Endocrinology', value: 'Endocrinology' },
  { label: 'Nephrology', value: 'Nephrology' },
  { label: 'Urology', value: 'Urology' },
  { label: 'Gastroenterology', value: 'Gastroenterology' },
  { label: 'Pulmonology', value: 'Pulmonology' },
  { label: 'Rheumatology', value: 'Rheumatology' },
  { label: 'Physiotherapy', value: 'Physiotherapy' },
  { label: 'Nutrition and Dietetics', value: 'Nutrition and Dietetics' },
  { label: 'Nursing', value: 'Nursing' },
  { label: 'Triage', value: 'Triage' },
  { label: 'Laboratory', value: 'Laboratory' },
  { label: 'Pharmacy', value: 'Pharmacy' },
  { label: 'Front Desk', value: 'Front Desk' },
  { label: 'Records Department', value: 'Records Department' },
  { label: 'Administration', value: 'Administration' },
];
